### ISSUE TITLE
When configuring a cache both ttl and max capacity must be present

### ISSUE THREAD

**Issue by sbglasius** [itds-ch/grails-cache-guava#2]
If you configure a set of caches like this:

```
grails:
    cache:
        guava:
            defaultTtl: 300
            caches:
                demo:
                    maxCapacity: 10
                    ttl: 10
                cache1:
                    ttl: 10
                cache2:
                    maxCapacity: 20
```
it will fail on startup.

In the pull-request that I have submitted, it is possible to add `defaultMaxCapacity`, `defaultAllowNullValues` and `allowNullValues`  for caches individually. 

It will allow a the above configuration to be read, and also this:
```
grails:
    cache:
        guava:
            defaultTtl: 300
            defaultMaxCapacity: 2000
            caches:
                demo:
                    maxCapacity: 10
                    ttl: 10
                cache1:
                    ttl: 10
                cache2:
                    maxCapacity: 20
                cache3:
                    allowNullValues: false
```
